image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

variables:
  TAG: preprod-$CI_COMMIT_SHORT_SHA

before_script:
  - echo "$ec2_ssh_key" > deploy_key && chmod 600 deploy_key

test:
  stage: test
  only:
    - devloppeur
  image: python:3.9  # Utilisation d'une image avec Python pour installer Locust
  before_script:
    - apt-get update && apt-get install -y curl nodejs npm  # Installer Node.js et npm
    - npm install
    - pip3 install locust  # Installer Locust
  script:
    - npm test  # Lancer les tests Jest
    - npm start &  # Démarrer le backend en arrière-plan
    - sleep 5  # Attendre que le serveur démarre
    - locust --headless --users 100 --spawn-rate 80 -H http://localhost:3000 -t 5s --only-summary




build-docker-compose:
  stage: build
  script:
    - echo "$env" > .env
    - docker-compose -f docker-compose.yml build

  only:
    - main

deploy:
  stage: deploy
  script:
    - scp -i deploy_key docker-compose.yml .env $ec2_user_preprod@$ec2_ip_preprod:$app_directory
    - ssh -i deploy_key $ec2_user@$ec2_ip_preprod <<EOF
        cd $app_directory
        docker-compose pull
        docker-compose down
        docker-compose up -d
      EOF
  only:
    - main
