image: debian:latest


stages:
  - build
  - deploy 
  - test
  - Sonar_analysis  # Ajout de l'analyse SonarClouds

variables:
  APP_DIR: "/home/admin/app"
  SONAR_TOKEN: $SONAR_TOKEN
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0" 
  TAG: $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
  PREPRD_TAG: $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA 
  DOCKER_IMAGE_PROD: ahmedgribi/morningnews-backend-projet_final
  DOCKER_IMAGE_PREPROD: ahmedgribi/morningnews-backend-projet_final



 
before_script:
  - echo "$ec2_ssh_key" > deploy_key && chmod 600 deploy_key
  - apt-get update && apt-get install -y docker.io
  - echo $Token_docker | docker login -u $Login_Docker --password-stdin



build_preprod:
  stage: build
  script:
    - echo "CONNECTION_STRING=$CONNECTION_STRING_PREPROD" > .env
    - echo "NEWS_API_KEY=$NEWS_API_KEY" >> .env
    - docker build -t $DOCKER_IMAGE_PREPROD:$PREPRD_TAG .
    - docker push $DOCKER_IMAGE_PREPROD:$PREPRD_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

  tags:
  - linux

build_prod: 
  stage: build
  script:
    - echo "CONNECTION_STRING=$CONNECTION_STRING" > .env
    - echo "NEWS_API_KEY=$NEWS_API_KEY" >> .env
    - docker build -t $DOCKER_IMAGE_PROD:$TAG -t $DOCKER_IMAGE_PROD:latest .
    - docker push $DOCKER_IMAGE_PROD:$TAG
    - docker push $DOCKER_IMAGE_PROD:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "production"



deploy_preprod:
  stage: deploy
  script:
    - echo "Deploying application in PREPRD's instance"
    - mv docker-compose-bdd-preprod.yml docker-compose-bdd.yml
    - echo "CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH}" > deploy_env.tmp
    - echo "CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}" >> deploy_env.tmp
    - echo "MONGO_INITDB_ROOT_USERNAME=$mongo_user" >> deploy_env.tmp
    - echo "MONGO_INITDB_ROOT_PASSWORD=$mongo_password" >> deploy_env.tmp
    - rsync -avv --progress -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i deploy_key" docker-compose.yml deploy_env.tmp Dockerfile nginx.conf mongo-init.js docker-compose-bdd.yml $ec2_user@$ec2_ip_preprod:$APP_DIR
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i deploy_key $ec2_user@$ec2_ip_preprod "export PATH=\$PATH:/usr/local/bin && mv ~/app/deploy_env.tmp .env && cd $APP_DIR && sudo docker compose down && sudo docker compose up -d --pull always"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
   - linux

deploy_prod:

  stage: deploy
  script:
    - echo "Deploying application in production's instance"
    - echo "services:" > docker-compose-bdd.yml
    - echo "CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH}" > deploy_env.tmp
    - echo "CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}" >> deploy_env.tmp
    - rsync -avv --progress -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i deploy_key" docker-compose.yml deploy_env.tmp Dockerfile nginx.conf mongo-init.js docker-compose-bdd.yml $ec2_user@$ec2_ip:$APP_DIR
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i deploy_key $ec2_user@$ec2_ip "export PATH=\$PATH:/usr/local/bin && cd $APP_DIR && mv ~/app/deploy_env.tmp .env && sudo docker compose down && sudo docker compose up -d --pull always"
  rules:
    - if: $CI_COMMIT_BRANCH == "production"




test:
  stage: test
  only:
    - devloppeur
  image: python:3.9  # Utilisation d'une image avec Python pour installer Locust
  before_script:
    - apt-get update && apt-get install -y curl nodejs npm python3-venv # Installer Node.js et npm
    - npm install
    - python3 -m venv locust-env
    - source locust-env/bin/activate
    - pip3 install locust
    - echo "$CONNECTION_STRING"
    - echo "$CONNECTION_STRING" > .env 
    
  script:
    - npm start &
    - npm test -- --coverage  #  Génération du rapport de couverture Jest
    - sleep 5  # Attendre que le serveur démarre
    - locust --headless --users 100 --spawn-rate 80 -H http://localhost:3000 -t 5s --only-summary
  artifacts:
    paths:
      - coverage/lcov.info  # Sauvegarde le rapport pour l'analyse SonarCloud
    expire_in: 1 hour  # Les fichiers sont stockés temporairement


sonarcloud-check:
  stage: Sonar_analysis
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner #-Dsonar.branch.name=$CI_COMMIT_BRANCH
  only:
    - devloppeur

