services:  
  bdd:
    image: mongodb:latest
    container_name: bdd_morningnews
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=$mongo_password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - back-network