services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ahmedgribi/morningnews-backend-projet_final:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
    container_name: frontend_morningnews
    restart: always
    environment:
      - CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH}
      - CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
    ports:
      - "3000:3000"
    networks:
      - back-network

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./empty.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/share/nginx/html
    container_name: nginx_morningnews_proxy
    depends_on:
      - app
    ports:
      - "443:443"
      - "80:80"
    networks:
      - back-network
    
include:
  - docker-compose-bdd.yml

networks:
  back-network:
    driver: bridge
    
