version: "3.9"

services:
  app:
    image: ahmedgribi/morningnews-backend-projet_final:preprod-$CI_COMMIT_SHORT_SHA
    container_name: backend_morningnews
    env_file:
      - .env
    ports:
      - "3000:3000"  
  
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_morningnews_proxy
    ports:
      - "443:443"
      - "80:80"
    
